import React from 'react';
import {ScrollView, Text, View} from "react-native";
import Menu from "../components/Menu";
import Footer from "../components/Footer";

function About(props) {
    return (
       <View>
           <ScrollView>
               <Text>
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam doloremque eius esse impedit ipsum libero minima natus officia possimus repellat sunt tempore voluptates, voluptatibus! Autem cumque est illum maiores minima quis sed totam, velit? Accusantium aliquid amet aperiam asperiores consequuntur culpa debitis deserunt dicta dignissimos distinctio eligendi enim eos eum eveniet facere fugit impedit in inventore ipsam itaque minima neque nobis non odio perspiciatis placeat provident quo recusandae rerum saepe sed tempore totam unde, vel velit voluptate voluptatem! Amet aspernatur, corporis deserunt, dicta eos expedita explicabo ipsam ipsum minus nesciunt odio quam ratione rem repellat suscipit temporibus tenetur. Ab alias at beatae commodi cumque dolore eveniet explicabo id impedit in itaque labore laudantium nam nesciunt nisi nobis nostrum, optio perspiciatis quaerat quasi recusandae, soluta ullam ut vel, voluptatum. Adipisci aperiam autem cumque dolorum et necessitatibus neque nisi, quidem quos ratione repellendus reprehenderit soluta tenetur? Eaque, magni, temporibus. Accusamus consequuntur distinctio doloribus eos, et illum modi nobis praesentium qui quod repellat sapiente! A ea eligendi maxime neque nihil perspiciatis qui, rerum voluptate. Cumque, laudantium, praesentium? Aliquid, asperiores at autem blanditiis consectetur consequatur dolorum ea et ex exercitationem ipsam iste minima modi nesciunt odio officiis optio perferendis, possimus provident sit tenetur unde.
               </Text>
               <Text>
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam doloremque eius esse impedit ipsum libero minima natus officia possimus repellat sunt tempore voluptates, voluptatibus! Autem cumque est illum maiores minima quis sed totam, velit? Accusantium aliquid amet aperiam asperiores consequuntur culpa debitis deserunt dicta dignissimos distinctio eligendi enim eos eum eveniet facere fugit impedit in inventore ipsam itaque minima neque nobis non odio perspiciatis placeat provident quo recusandae rerum saepe sed tempore totam unde, vel velit voluptate voluptatem! Amet aspernatur, corporis deserunt, dicta eos expedita explicabo ipsam ipsum minus nesciunt odio quam ratione rem repellat suscipit temporibus tenetur. Ab alias at beatae commodi cumque dolore eveniet explicabo id impedit in itaque labore laudantium nam nesciunt nisi nobis nostrum, optio perspiciatis quaerat quasi recusandae, soluta ullam ut vel, voluptatum. Adipisci aperiam autem cumque dolorum et necessitatibus neque nisi, quidem quos ratione repellendus reprehenderit soluta tenetur? Eaque, magni, temporibus. Accusamus consequuntur distinctio doloribus eos, et illum modi nobis praesentium qui quod repellat sapiente! A ea eligendi maxime neque nihil perspiciatis qui, rerum voluptate. Cumque, laudantium, praesentium? Aliquid, asperiores at autem blanditiis consectetur consequatur dolorum ea et ex exercitationem ipsam iste minima modi nesciunt odio officiis optio perferendis, possimus provident sit tenetur unde.
               </Text>
               <Text>
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam doloremque eius esse impedit ipsum libero minima natus officia possimus repellat sunt tempore voluptates, voluptatibus! Autem cumque est illum maiores minima quis sed totam, velit? Accusantium aliquid amet aperiam asperiores consequuntur culpa debitis deserunt dicta dignissimos distinctio eligendi enim eos eum eveniet facere fugit impedit in inventore ipsam itaque minima neque nobis non odio perspiciatis placeat provident quo recusandae rerum saepe sed tempore totam unde, vel velit voluptate voluptatem! Amet aspernatur, corporis deserunt, dicta eos expedita explicabo ipsam ipsum minus nesciunt odio quam ratione rem repellat suscipit temporibus tenetur. Ab alias at beatae commodi cumque dolore eveniet explicabo id impedit in itaque labore laudantium nam nesciunt nisi nobis nostrum, optio perspiciatis quaerat quasi recusandae, soluta ullam ut vel, voluptatum. Adipisci aperiam autem cumque dolorum et necessitatibus neque nisi, quidem quos ratione repellendus reprehenderit soluta tenetur? Eaque, magni, temporibus. Accusamus consequuntur distinctio doloribus eos, et illum modi nobis praesentium qui quod repellat sapiente! A ea eligendi maxime neque nihil perspiciatis qui, rerum voluptate. Cumque, laudantium, praesentium? Aliquid, asperiores at autem blanditiis consectetur consequatur dolorum ea et ex exercitationem ipsam iste minima modi nesciunt odio officiis optio perferendis, possimus provident sit tenetur unde.
               </Text>
               <Text>
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam doloremque eius esse impedit ipsum libero minima natus officia possimus repellat sunt tempore voluptates, voluptatibus! Autem cumque est illum maiores minima quis sed totam, velit? Accusantium aliquid amet aperiam asperiores consequuntur culpa debitis deserunt dicta dignissimos distinctio eligendi enim eos eum eveniet facere fugit impedit in inventore ipsam itaque minima neque nobis non odio perspiciatis placeat provident quo recusandae rerum saepe sed tempore totam unde, vel velit voluptate voluptatem! Amet aspernatur, corporis deserunt, dicta eos expedita explicabo ipsam ipsum minus nesciunt odio quam ratione rem repellat suscipit temporibus tenetur. Ab alias at beatae commodi cumque dolore eveniet explicabo id impedit in itaque labore laudantium nam nesciunt nisi nobis nostrum, optio perspiciatis quaerat quasi recusandae, soluta ullam ut vel, voluptatum. Adipisci aperiam autem cumque dolorum et necessitatibus neque nisi, quidem quos ratione repellendus reprehenderit soluta tenetur? Eaque, magni, temporibus. Accusamus consequuntur distinctio doloribus eos, et illum modi nobis praesentium qui quod repellat sapiente! A ea eligendi maxime neque nihil perspiciatis qui, rerum voluptate. Cumque, laudantium, praesentium? Aliquid, asperiores at autem blanditiis consectetur consequatur dolorum ea et ex exercitationem ipsam iste minima modi nesciunt odio officiis optio perferendis, possimus provident sit tenetur unde.
               </Text>
               <Text>
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam doloremque eius esse impedit ipsum libero minima natus officia possimus repellat sunt tempore voluptates, voluptatibus! Autem cumque est illum maiores minima quis sed totam, velit? Accusantium aliquid amet aperiam asperiores consequuntur culpa debitis deserunt dicta dignissimos distinctio eligendi enim eos eum eveniet facere fugit impedit in inventore ipsam itaque minima neque nobis non odio perspiciatis placeat provident quo recusandae rerum saepe sed tempore totam unde, vel velit voluptate voluptatem! Amet aspernatur, corporis deserunt, dicta eos expedita explicabo ipsam ipsum minus nesciunt odio quam ratione rem repellat suscipit temporibus tenetur. Ab alias at beatae commodi cumque dolore eveniet explicabo id impedit in itaque labore laudantium nam nesciunt nisi nobis nostrum, optio perspiciatis quaerat quasi recusandae, soluta ullam ut vel, voluptatum. Adipisci aperiam autem cumque dolorum et necessitatibus neque nisi, quidem quos ratione repellendus reprehenderit soluta tenetur? Eaque, magni, temporibus. Accusamus consequuntur distinctio doloribus eos, et illum modi nobis praesentium qui quod repellat sapiente! A ea eligendi maxime neque nihil perspiciatis qui, rerum voluptate. Cumque, laudantium, praesentium? Aliquid, asperiores at autem blanditiis consectetur consequatur dolorum ea et ex exercitationem ipsam iste minima modi nesciunt odio officiis optio perferendis, possimus provident sit tenetur unde.
               </Text>
               <Footer/>
           </ScrollView>
       </View>
    );
}

export default About;